### ISSUE TITLE
Cpp端反射生成CBuffer可能存在内存问题

### ISSUE THREAD

**Issue by AlvinRey** [MKXJun/DirectX11-With-Windows-SDK#10]
可能存在bug的代码段 EffectHelper.cpp Lines 646~651

某一个Effect中存在两个Shader：Shader1和Shader2
有一个CBuffer内有若干个成员变量，但Shader1只使用了其中的某几个，C++段反射生成的Buffer的buffer size大小并不是完整的CBuffer的大小。（我的情况：CBuffer完整应是576bytes，但Shader1反射生成的Buffer只有560bytes）

而Shader2使用了完整的CBuffer，反射生成的Buffer大小为完整CBuffer大小（我的情况：Shader2反射生成的Buffer为576bytes）。但是因为在m_CBuffers中已经存在BindPoint相同的Buffer，所以Shader2反射生成的Buffer并没有覆盖到m_CBuffers中。

最终我的情况：渲染是没有问题的，但在关闭程序，析构CBufferData中的cbufferData数组（在m_CBuffers[x]中）时，会报内存越界的错误 (error: crt detected that the application wrote to memory after end of heap buffer)。

我的解决方法：

Lines 647 
`if (it == m_CBuffers.end()) 改成 if (it == m_CBuffers.end() || it->second.cbufferData.size() < cbDesc.Size)`

Lines 649
`m_CBuffers.emplace(...)`
改成
`if (!m_CBuffers.emplace(...).second)
{
    m_CBuffers[sibDesc.BindPoint] = CBufferData(...);
}`

这样改的话对于目前我的项目来说是没有报内存越界的错了。
因为我的水平有限，这样改目前还不知道会不会引起其他问题。
如果有，请回复告知我一下，谢谢。

**Comment by AlvinRey** [comment]
似乎找到原因了，是因为cso没更新。
Shader1用的cso是没有修改CBuffer之前编译的，Shader2用的是修改CBuffer之后的编译的cso。
这样的话似乎要在编译Shader时，除了检查是否存在cso，还要检查是否是最新版本。

**Comment by MKXJun** [comment]
建议在写shader的时候用`m_pEffectHelper->SetBinaryCacheDirectory(cacheDir, true);`保持在cacheDir强制编译生成cso，稳定以后最后一个参数可以false。参考31章后代码。
