### ISSUE TITLE
交换链更换翻转模型后，拉伸窗口出现白边

### ISSUE THREAD

**Issue by MKXJun** [MKXJun/DirectX11-With-Windows-SDK#9]
交换链更换FLIP Model后，拉伸窗口会在窗口右下角出现白边
![image](https://user-images.githubusercontent.com/18623921/170021353-d7131fb4-8b9e-4ab2-b06d-9c02e20cdbf1.png)

然后再拖动一下窗口好像就没掉了。刚找到一篇文章，后续参考着看看能不能解决这个问题
https://www.gamedev.net/forums/topic/708865-dxgi-flip-model-flickering-during-live-resize/

**Comment by Demonese** [comment]
拖动窗口时，多出来的区域会出现白边（如果是拖动让窗口变小当然不存在这个问题）。
这个问题很多程序都有，连unity hub都不可避免，我认为它确实是一种特性，不用特意处理。

**Comment by MKXJun** [comment]
目前很长一段时间暂时没有复现出问题，可能是前面改了什么代码好了。后续出问题再看看
